"""Records for the migration knowledge base: the systems a migration touches and how they depend on one another.

A knowledge base holds two kinds of record. A node is a thing that exists in
the source or target platform, such as a repository, a pipeline, an artifact
feed or a service connection. An edge is a dependency between two of them,
always written in one direction: the consumer first, the thing it depends on
second. Reading the edges forwards answers "what does this need"; reading them
backwards answers "what would notice if this moved".

Every edge carries where the fact came from and when it was last seen, because
an answer built on a scan from three weeks ago is worth less than one built on
a scan from this morning, and the reader has to be able to tell the difference.
Nothing here reaches a database or a network; these are plain records that the
store and the builder both use, so neither has to know the other's internals.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional


class NodeKind(str, Enum):
    """What a node in the knowledge base is.

    A string enum so a stored value reads the same in the database, in an
    answer to the operator and in a message to a language model.
    """

    REPOSITORY = "repository"
    PIPELINE = "pipeline"
    RELEASE_PIPELINE = "release_pipeline"
    ARTIFACT_FEED = "artifact_feed"
    SERVICE_CONNECTION = "service_connection"
    VARIABLE_GROUP = "variable_group"
    SECURE_FILE = "secure_file"
    ENVIRONMENT = "environment"
    AGENT_POOL = "agent_pool"
    CONTAINER_IMAGE = "container_image"
    WIKI = "wiki"
    WORK_ITEM_PROJECT = "work_item_project"
    TEST_PLAN = "test_plan"
    UNKNOWN = "unknown"


class EdgeKind(str, Enum):
    """How one thing depends on another.

    Each member reads as a sentence from the consumer to the dependency: a
    pipeline *builds* a repository, a pipeline *consumes artifact of* another
    pipeline, a repository *needs credential* held by a service connection.
    """

    BUILDS = "builds"
    CHECKS_OUT = "checks_out"
    EXTENDS_TEMPLATE_IN = "extends_template_in"
    CONSUMES_ARTIFACT_OF = "consumes_artifact_of"
    CONSUMES_FEED = "consumes_feed"
    TRIGGERED_BY = "triggered_by"
    NEEDS_CREDENTIAL = "needs_credential"
    NEEDS_VARIABLE_GROUP = "needs_variable_group"
    NEEDS_SECURE_FILE = "needs_secure_file"
    DEPLOYS_TO = "deploys_to"
    RUNS_ON_POOL = "runs_on_pool"
    USES_CONTAINER = "uses_container"


class Confidence(str, Enum):
    """How firmly a recorded dependency is believed.

    ``DECLARED`` means the source named it outright, such as a template
    reference that gives the repository it lives in. ``RESOLVED`` means the
    platform matched a name to a known thing and the match was unambiguous.
    ``INFERRED`` means a heuristic found it, such as a connection name spotted
    in free text, and it may be wrong. An answer must never present an
    inferred dependency as though it were declared.
    """

    DECLARED = "declared"
    RESOLVED = "resolved"
    INFERRED = "inferred"


class EdgeStatus(str, Enum):
    """Whether a dependency was still present the last time its source was read."""

    ACTIVE = "active"
    DISAPPEARED = "disappeared"


def utc_now_text() -> str:
    """Return the current coordinated universal time as a sortable text stamp.

    Returns:
        The current time in coordinated universal time, in the same text form
        the rest of the state store uses, so stamps compare as plain strings.
    """
    return datetime.now(timezone.utc).isoformat()


@dataclass(frozen=True)
class KnowledgeNode:
    """One thing a migration touches.

    Two nodes are the same thing when their profile, system, organisation,
    project, kind and identity key match. The identity key is the most stable
    name the source offers: an identifier where the source has one, and a
    normalised name where it does not.

    Attributes:
        node_id: Identifier generated by this platform, stable across scans
            for the same thing.
        profile_id: Migration profile the record belongs to, so two profiles
            scanning different organisations never read each other's facts.
        system: Platform the thing lives in, such as the source or the target.
        organization: Organisation or account the thing belongs to.
        project: Project within the organisation, empty where the thing sits
            above project level.
        kind: What the thing is.
        identity_key: Most stable name available, used for matching.
        external_id: Identifier the source system uses, empty when unknown.
        name: Human-readable name for an answer or a report.
        url: Address of the thing in its own system, empty when unknown.
        source_locator: Where this record was read from, such as a pipeline
            definition identifier and a file path.
        first_seen_at: When this platform first recorded the thing.
        last_seen_at: When a scan last confirmed the thing still exists.
        last_scan_id: Scan that last confirmed it.
    """

    node_id: str
    profile_id: str
    system: str
    organization: str
    project: str
    kind: NodeKind
    identity_key: str
    external_id: str = ""
    name: str = ""
    url: str = ""
    source_locator: str = ""
    first_seen_at: str = ""
    last_seen_at: str = ""
    last_scan_id: str = ""


@dataclass(frozen=True)
class KnowledgeEdge:
    """One dependency, written from the consumer to the thing it depends on.

    Attributes:
        edge_id: Identifier generated by this platform.
        profile_id: Migration profile the record belongs to.
        source_node_id: The consumer, the thing that would notice if the other
            end changed.
        target_node_id: The dependency, the thing being relied on.
        kind: How the consumer depends on the target.
        confidence: How firmly the dependency is believed.
        extraction_method: Name of the code path that found it, so a later
            reader can judge the evidence and a mistaken heuristic can be
            traced to its source.
        source_locator: Where the fact was read from.
        source_revision: Commit or definition version the fact was read at,
            empty when the source offers none.
        evidence: Small, already-masked details that justify the edge, such as
            the template path or the step name. Never holds a secret value.
        status: Whether the dependency was still there at the last scan.
        first_seen_at: When this platform first recorded the dependency.
        last_seen_at: When a scan last confirmed it.
        last_scan_id: Scan that last confirmed it.
    """

    edge_id: str
    profile_id: str
    source_node_id: str
    target_node_id: str
    kind: EdgeKind
    confidence: Confidence = Confidence.DECLARED
    extraction_method: str = ""
    source_locator: str = ""
    source_revision: str = ""
    evidence: dict[str, Any] = field(default_factory=dict)
    status: EdgeStatus = EdgeStatus.ACTIVE
    first_seen_at: str = ""
    last_seen_at: str = ""
    last_scan_id: str = ""


@dataclass(frozen=True)
class KnowledgeScan:
    """One pass of reading a source, and what it managed to cover.

    Coverage is recorded because it is the difference between "nothing depends
    on this" and "nothing that this scan could see depends on this". An answer
    quotes the coverage so the reader knows which of the two they are holding.

    Attributes:
        scan_id: Identifier generated by this platform.
        profile_id: Migration profile the scan belongs to.
        source_scope: What was asked for, such as an organisation or a single
            project.
        extractor_version: Version of the extraction code that ran, so facts
            from an older parser can be found and re-read.
        started_at: When the scan began.
        completed_at: When it finished, empty while it is still running.
        status: How it ended.
        coverage: What it looked at and what it could not look at, such as the
            number of pipeline definitions read and the ones that could not be
            parsed.
        error_summary: Short, already-masked description of what went wrong,
            empty on success.
    """

    scan_id: str
    profile_id: str
    source_scope: str
    extractor_version: str
    started_at: str
    completed_at: str = ""
    status: str = "running"
    coverage: dict[str, Any] = field(default_factory=dict)
    error_summary: str = ""


@dataclass(frozen=True)
class ImpactFinding:
    """One thing affected by a change to the node that was asked about.

    Attributes:
        node: The affected thing.
        relation: Whether it is something the subject needs, something that
            needs the subject, or something both the subject and another
            consumer rely on.
        distance: How many dependency steps away it is; one means directly
            connected.
        path: The node identifiers walked to reach it, subject first, so an
            answer can show its working.
        weakest_confidence: The least certain edge on that path, because a
            chain is only as believable as its shakiest link.
        evidence: The evidence of the edges walked, in the same order as the
            path.
    """

    node: KnowledgeNode
    relation: str
    distance: int
    path: list[str] = field(default_factory=list)
    weakest_confidence: Confidence = Confidence.DECLARED
    evidence: list[dict[str, Any]] = field(default_factory=list)


@dataclass(frozen=True)
class ImpactReport:
    """The answer to "what does a change to this thing affect".

    Attributes:
        subject: The thing that was asked about, or ``None`` when the knowledge
            base holds no record of it.
        prerequisites: Things the subject depends on, which generally have to
            be in place before the subject can move.
        consumers: Things that depend on the subject and would notice if it
            moved or went away.
        shared_dependencies: Things the subject depends on that other consumers
            also depend on, which need coordinating rather than blocking.
        coverage: What the underlying scans covered, quoted so the reader can
            tell an empty answer from an unexamined one.
        caveats: Plain sentences naming what this answer cannot know, such as
            dependencies expressed in ways the platform does not parse.
        truncated: Whether the traversal stopped at its limit before running
            out of things to visit.
    """

    subject: Optional[KnowledgeNode]
    prerequisites: list[ImpactFinding] = field(default_factory=list)
    consumers: list[ImpactFinding] = field(default_factory=list)
    shared_dependencies: list[ImpactFinding] = field(default_factory=list)
    coverage: dict[str, Any] = field(default_factory=dict)
    caveats: list[str] = field(default_factory=list)
    truncated: bool = False


RELATION_PREREQUISITE = "prerequisite"
"""The subject depends on this thing, so it generally has to be ready first."""

RELATION_CONSUMER = "consumer"
"""This thing depends on the subject and would notice if the subject changed."""

RELATION_SHARED_DEPENDENCY = "shared_dependency"
"""The subject and at least one other consumer both depend on this thing."""

NO_RECORDED_DEPENDENCY_CAVEAT = (
    "This answer covers only dependencies recorded by the scans listed under "
    "coverage. A thing with no recorded dependency may still have one that was "
    "never scanned, or one expressed in a form this platform does not read."
)
"""The sentence every answer carries, so an empty result is never read as proof."""
